In [ ]:
# pip install numpy
# pip install pandas
# pip install scikit-learn
# conda install numpy, pandas, scikit-learn

In [44]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [45]:
data_pd = pd.read_csv("Advertising.csv", index_col = 0)

In [46]:
print(data_pd)

        TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]


In [47]:
data = np.array(data_pd)

In [48]:
print(data)

[[230.1  37.8  69.2  22.1]
 [ 44.5  39.3  45.1  10.4]
 [ 17.2  45.9  69.3   9.3]
 [151.5  41.3  58.5  18.5]
 [180.8  10.8  58.4  12.9]
 [  8.7  48.9  75.    7.2]
 [ 57.5  32.8  23.5  11.8]
 [120.2  19.6  11.6  13.2]
 [  8.6   2.1   1.    4.8]
 [199.8   2.6  21.2  10.6]
 [ 66.1   5.8  24.2   8.6]
 [214.7  24.    4.   17.4]
 [ 23.8  35.1  65.9   9.2]
 [ 97.5   7.6   7.2   9.7]
 [204.1  32.9  46.   19. ]
 [195.4  47.7  52.9  22.4]
 [ 67.8  36.6 114.   12.5]
 [281.4  39.6  55.8  24.4]
 [ 69.2  20.5  18.3  11.3]
 [147.3  23.9  19.1  14.6]
 [218.4  27.7  53.4  18. ]
 [237.4   5.1  23.5  12.5]
 [ 13.2  15.9  49.6   5.6]
 [228.3  16.9  26.2  15.5]
 [ 62.3  12.6  18.3   9.7]
 [262.9   3.5  19.5  12. ]
 [142.9  29.3  12.6  15. ]
 [240.1  16.7  22.9  15.9]
 [248.8  27.1  22.9  18.9]
 [ 70.6  16.   40.8  10.5]
 [292.9  28.3  43.2  21.4]
 [112.9  17.4  38.6  11.9]
 [ 97.2   1.5  30.    9.6]
 [265.6  20.    0.3  17.4]
 [ 95.7   1.4   7.4   9.5]
 [290.7   4.1   8.5  12.8]
 [266.9  43.8   5.   25.4]
 

In [49]:
model_simple = LinearRegression()

In [50]:
X = data[:, 0].reshape(-1,1)
y = data[:, 3]

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1234)

In [52]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[ 39.5]
 [284.3]
 [163.5]
 [ 44.5]
 [ 38. ]
 [220.5]
 [131.1]
 [216.4]
 [131.7]
 [ 59.6]
 [237.4]
 [109.8]
 [237.4]
 [171.3]
 [265.6]
 [134.3]
 [289.7]
 [230.1]
 [137.9]
 [121. ]
 [156.6]
 [239.3]
 [ 18.8]
 [276.7]
 [ 17.2]
 [  5.4]
 [ 85.7]
 [198.9]
 [ 38.2]
 [187.9]
 [ 75.3]
 [180.8]
 [248.8]
 [ 66.1]
 [165.6]
 [205. ]
 [ 96.2]
 [219.8]
 [ 48.3]
 [283.6]
 [255.4]
 [248.4]
 [193.2]
 [ 69.2]
 [232.1]
 [ 76.3]
 [199.1]
 [ 26.8]
 [177. ]
 [ 67.8]
 [175.1]
 [213.5]
 [109.8]
 [209.6]
 [222.4]
 [197.6]
 [ 94.2]
 [ 97.5]
 [110.7]
 [239.8]
 [ 93.9]
 [117.2]
 [ 53.5]
 [204.1]
 [ 90.4]
 [ 75.1]
 [ 73.4]
 [147.3]
 [ 17.2]
 [151.5]
 [218.5]
 [ 16.9]
 [220.3]
 [184.9]
 [ 17.9]
 [ 95.7]
 [ 74.7]
 [ 27.5]
 [199.8]
 [276.9]
 [ 80.2]
 [ 76.4]
 [216.8]
 [175.7]
 [141.3]
 [125.7]
 [142.9]
 [229.5]
 [ 11.7]
 [164.5]
 [292.9]
 [187.8]
 [228.3]
 [170.2]
 [104.6]
 [197.6]
 [139.2]
 [182.6]
 [ 43.1]
 [239.9]]
[10.8 15.  18.  10.4 10.9 20.1 18.  22.6 12.9  9.7 18.9 12.4 12.5 19.
 17.4 11.2 25.4 22.1 19.2 11.

In [53]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(100, 1)
(100,)
(100, 1)
(100,)


In [54]:
model_simple.fit(X_train, y_train)

LinearRegression()

In [55]:
model_simple.coef_ # beta_1

array([0.04746895])

In [56]:
model_simple.intercept_ # beta_0

7.502168478254276

In [57]:
y_pred = model_simple.predict(X_test)

In [58]:
mean_squared_error(y_test, y_pred)**0.5

3.3254504419649464

In [59]:
r2_score(y_test, y_pred)

0.6212776636819719

In [60]:
model_multiple = LinearRegression()

In [61]:
X = data[:, :3].reshape(-1, 3)
y = data[:, 3]

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1234)

In [63]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[ 39.5  41.1   5.8]
 [284.3  10.6   6.4]
 [163.5  36.8   7.4]
 [ 44.5  39.3  45.1]
 [ 38.   40.3  11.9]
 [220.5  33.2  37.9]
 [131.1  42.8  28.9]
 [216.4  41.7  39.6]
 [131.7  18.4  34.6]
 [ 59.6  12.   43.1]
 [237.4  27.5  11. ]
 [109.8  14.3  31.7]
 [237.4   5.1  23.5]
 [171.3  39.7  37.7]
 [265.6  20.    0.3]
 [134.3   4.9   9.3]
 [289.7  42.3  51.2]
 [230.1  37.8  69.2]
 [137.9  46.4  59. ]
 [121.    8.4  48.7]
 [156.6   2.6   8.3]
 [239.3  15.5  27.3]
 [ 18.8  21.7  50.4]
 [276.7   2.3  23.7]
 [ 17.2   4.1  31.6]
 [  5.4  29.9   9.4]
 [ 85.7  35.8  49.3]
 [198.9  49.4  60. ]
 [ 38.2   3.7  13.8]
 [187.9  17.2  17.9]
 [ 75.3  20.3  32.5]
 [180.8  10.8  58.4]
 [248.8  27.1  22.9]
 [ 66.1   5.8  24.2]
 [165.6  10.   17.6]
 [205.   45.1  19.6]
 [ 96.2  14.8  38.9]
 [219.8  33.5  45.1]
 [ 48.3  47.    8.5]
 [283.6  42.   66.2]
 [255.4  26.9   5.5]
 [248.4  30.2  20.3]
 [193.2  18.4  65.7]
 [ 69.2  20.5  18.3]
 [232.1   8.6   8.7]
 [ 76.3  27.5  16. ]
 [199.1  30.6  38.7]
 [ 26.8  33. 

In [64]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(100, 3)
(100,)
(100, 3)
(100,)


In [65]:
model_multiple.fit(X_train, y_train)

LinearRegression()

In [66]:
model_multiple.coef_

array([0.04650112, 0.18718697, 0.0002054 ])

In [67]:
y_pred = model_multiple.predict(X_test)

In [68]:
mean_squared_error(y_test, y_pred)

3.374274942310322

In [69]:
r2_score(y_test, y_pred)

0.8844418910002424